// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB7P8A2bCHrPn9kIG2ILKwXfrvKucUqSc',
    appId: '1:875680162335:web:96140a69b70eb2331f6b2a',
    messagingSenderId: '875680162335',
    projectId: 'savvy-surge-444401-p3',
    authDomain: 'savvy-surge-444401-p3.firebaseapp.com',
    storageBucket: 'savvy-surge-444401-p3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-CT34LYlEfErt16PRiV1r7eqU-d1sbFs',
    appId: '1:875680162335:android:3f3b199aefe3641c1f6b2a',
    messagingSenderId: '875680162335',
    projectId: 'savvy-surge-444401-p3',
    storageBucket: 'savvy-surge-444401-p3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWH_tVD2BQ8mwsvkJvvTqA58qVYzN_dAo',
    appId: '1:875680162335:ios:e2ec9efc74544a3b1f6b2a',
    messagingSenderId: '875680162335',
    projectId: 'savvy-surge-444401-p3',
    storageBucket: 'savvy-surge-444401-p3.firebasestorage.app',
    androidClientId: '875680162335-62j9ur4uplk5jn1htpciu0pprkpt3ndl.apps.googleusercontent.com',
    iosClientId: '875680162335-b7mcpri3qotojij3kns17n98sc7k06rb.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWH_tVD2BQ8mwsvkJvvTqA58qVYzN_dAo',
    appId: '1:875680162335:ios:e2ec9efc74544a3b1f6b2a',
    messagingSenderId: '875680162335',
    projectId: 'savvy-surge-444401-p3',
    storageBucket: 'savvy-surge-444401-p3.firebasestorage.app',
    androidClientId: '875680162335-62j9ur4uplk5jn1htpciu0pprkpt3ndl.apps.googleusercontent.com',
    iosClientId: '875680162335-b7mcpri3qotojij3kns17n98sc7k06rb.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB7P8A2bCHrPn9kIG2ILKwXfrvKucUqSc',
    appId: '1:875680162335:web:97eb655e45a395611f6b2a',
    messagingSenderId: '875680162335',
    projectId: 'savvy-surge-444401-p3',
    authDomain: 'savvy-surge-444401-p3.firebaseapp.com',
    storageBucket: 'savvy-surge-444401-p3.firebasestorage.app',
  );
}
